sudo: required
services: 
    - docker

before_install:
    - docker build -t jayshah/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jayshah/docker-react npm run test -- --coverage
